baseURL = "https://dav1dsec.github.io/"
languageCode = "en-us"
title = "Welcome to my blog!"
theme = "nightfall"
enableRobotsTXT = true
preserveTaxonomyNames = true

[pagination]
  pagerSize = 5

[module]
  [module.hugoVersion]
    min = "0.146.0"

[taxonomies]
  category = "categories"
  platform = "platforms"
  series = "series"
  tag = "tags"

[params]
  darkmode = true
  favicon = "images/favicon.ico"
  user = "dav1dsec"
  hostname = "blog"
  openLinksInNewTab = true
  displayDateFormat = "2006-01-02"
  showMetadata = true
  showPublishedDate = true
  showReadingTime = true
  showTags = true
  showAuthors = true
  showCategories = true

  [params.author]
    name = "david"
    description = "Welcome to my security blog. Feel free to connect with me below :)"
    email = ""
   
  
  [[params.social]]
    key = 1
    name = "linkedin"
    url = "https://www.linkedin.com/in/dcrochester"
  
  [[params.social]]
    key = 2
    name = "github"
    url = "https://github.com/dav1dsec"
    rel = "me"
  
  [[params.social]]
    key = 3
    name = "hackthebox"
    url = "https://app.hackthebox.com/users/2162131"
  
  [params.styles]
    color = "cyan"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts/"
  
  [[menu.header]]
    name = "categories"
    weight = 1
    url = "/categories/"
  
  [[menu.header]]
    name = "about"
    weight = 2
    url = "/about/"

[markup]
  [markup.highlight]
    style = "monokai"
  
  [markup.sass]
    implementation = "sass"